name: Create Pull Request For New Post

on:
  create:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Pull Request
      run:
        gh pr create --title 'Create Pull Request For New Post' --body "`cat .github/pull_request_for_new_post_template.md`"
