name: Create Pull Request For New Post

on:
  create:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Pull Request
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = `New PR from ${github.context.payload.sender.login}`;
          const body = `
          related #

          ## やったこと

          _TODO_

          ## やらなかったこと（敢えてやらなかったことがあれば。issueも作れると良いかも？）

          _TODO_
          
          `;
          const { data: pr } = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            body,
            head: context.ref,
            base: 'main'
          });
          console.log(`Created PR: ${pr.html_url}`);
